version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle.kts" }}
          - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      - run: ./gradlew :consumer-android:app:assembleDebug

      - run: ./gradlew :consumer-server:server:appengineStage

      - run: ./gradlew  test collectUnitTest

      - store_test_results:
                path: build/reports/tests/
      - store_artifacts:
                path: build/reports/tests/
